### ISSUE TITLE
Null Thumbnail Value throws NPE

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#123]
Thumbnails can be null if removed by Reddit (see [this link](https://www.reddit.com/r/pussypassdenied/comments/4b85hi/vile_bitch_gets_exposed_by_herself_on_facebook/.json), ignore the content (found the issue going through /r/all on Slide)), and therefore throw an NPE when trying to access getThumbnailType() in the Submission class. 

A quick fix would be to check if the string "thumb" is null, or check if the json type is null.

**Comment by zglazer** [comment]
Is null thumbnail a ThumbnailType.NONE or do we need a new ThumbnailType?

**Comment by ccrama** [comment]
@zglazer  There needs to be a new ThumbnailType for null thumbnails as .getTextValue() [here](https://github.com/thatJavaNerd/JRAW/blob/b4b42de1d02632ae039272ce4f30e3d95476caa4/src/main/java/net/dean/jraw/models/Submission.java#L199) throws an NPE. At the top, doing if(!data.has("thumbnail")) type = ThumbnailType.NONE; should be able to kill two birds with one stone

**Comment by zglazer** [comment]
@ccrama I must have worded my question poorly. Should a null thumbnail be a ThumnailType.NONE or do we want to have a new type such as ThumnailType.REMOVED to describe the thumbnail? I am not very familiar with Reddit's usage of a null thumbnail so I want to make sure we aren't hiding information that may be needed by the client. I understand the current behavior.

**Comment by ccrama** [comment]
@zglazer  Ah, gotcha. Actually considering that it's only null if removed, I think a new ThumbnailType would be the better solution!

**Comment by zglazer** [comment]
I can't seem to make up my mind on this one. However, the documentation in JRAW seems pretty clear that the enum ThumbnailType represents possible return values from the Reddit API. Looking at the Reddit [source code](https://github.com/reddit/reddit/blob/24ddd3491e6dc0ed6f9e61e785adeb6a8bb64cea/r2/r2/models/link.py) there is currently no special handling for "removed" thumbnails. They are treated as None (null).

Unless anybody thinks otherwise, I will represent a null thumbnail as Thumbnail.NONE. This ensures consistency.

**Comment by ccrama** [comment]
Sounds good, might want to see what @thatJavaNerd  thinks about it as well

**Comment by thatJavaNerd** [comment]
IMHO using `ThumbnailType.NONE` would be better under most circumstances. @ccrama are there any specific cases in which it is important to distinguish between having no thumbnail and having one that has been removed?

**Comment by ccrama** [comment]
Honestly probably not @thatJavaNerd , NONE would work fine
