### ISSUE TITLE
Revoke response throws an exception

### ISSUE THREAD

**Issue by malsabbagh** [thatJavaNerd/JRAW#126]
According to [reddit API](https://github.com/reddit/reddit/wiki/OAuth2), the response for revoke will always be 204 with a "No Content" message.
Because of that, the library crashes in the following area
https://github.com/thatJavaNerd/JRAW/blob/b4b42de1d02632ae039272ce4f30e3d95476caa4/src/main/java/net/dean/jraw/http/RestResponse.java#L49

Can someone have a look?

I am using version 0.8.0

**Comment by malsabbagh** [comment]
The stacktrace for reference. 
java.lang.IllegalStateException: No Content-Type header was found
at net.dean.jraw.http.RestResponse.<init>(RestResponse.java:49)
at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:66)
at net.dean.jraw.http.RestClient.execute(RestClient.java:120)
at net.dean.jraw.RedditClient.execute(RedditClient.java:159)
at net.dean.jraw.RedditClient.execute(RedditClient.java:153)
at net.dean.jraw.http.oauth.OAuthHelper.revokeToken(OAuthHelper.java:288)
at net.dean.jraw.http.oauth.OAuthHelper.revokeAccessToken(OAuthHelper.java:264)
at java.lang.Thread.run(Thread.java:818)

**Comment by michaelvas** [comment]
Same thing here. I double checked the behavior of https://www.reddit.com/api/v1/revoke_token using Postman and successful response has 204 code and no 'Content-Type' header.

**Comment by zglazer** [comment]
It looks like we don't even need the RestResponse object created by `reddit.execute()` [here](https://github.com/thatJavaNerd/JRAW/blob/b4b42de1d02632ae039272ce4f30e3d95476caa4/src/main/java/net/dean/jraw/http/oauth/OAuthHelper.java#L287). I don't really want to band-aid the solution but should we maybe just catch the exception in `revokeToken()` as an easy fix?

**Comment by thatJavaNerd** [comment]
It might be a better approach to fix the `RestResponse` constructor instead of `revokeToken`. Catching the exception in `revokeToken()` would fix the problem, but only for that specific instance. Any other endpoints that return a 204 No Content and provide no Content-Type header will have the same problem.

**Comment by zglazer** [comment]
I see two options here for creating a proper 204 `RestResponse`.

1. We can set the `MediaType` on a 204 RestResponse to `MediaType.ANY_TYPE` to prevent some immediate errors thrown by `JrawUtils.isEqual()` and the `RestResponse` constructor.


2. Set the `MediaType` to null. We can update `RestClient.execute()` to manually check for a 204 but then we may be dealing with a null `MediaType` throughout the library.

I do not know the http layer enough to know which is the best solution. I lean towards option 1 because I would hate the introduce new errors stemming from a null `MediaType`. However, quick research shows a 204 response should not technically have a `MediaType`.
