### ISSUE TITLE
Authentication failure when requesting a Submission

### ISSUE THREAD

**Issue by radonthetyrant** [thatJavaNerd/JRAW#127]
I'm trying to read a public submission, which is also accessible via public url https://www.reddit.com/r/announcements/comments/4dmnn6/.json
When trying to read the submission via JRAW api, a 403 Unauthorized gets thrown.

Is there any way around this, to get Submissions through the API without authorizing the app?

**Comment by thatJavaNerd** [comment]
Reddit has [deprecated cookie-based authentication](https://www.reddit.com/wiki/api), which is what that URL relies on. OAuth-based authentication requires every single client to be authorized in order to access any data on the site. Since JRAW is an OAuth-only library, you must authenticate your client. If your app/script does not need a user to be logged in, you can use application-only OAuth. See more in [the wiki](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2#script-and-application-only).

**Comment by radonthetyrant** [comment]
Great, that solves the issue. Thanks!
