### ISSUE TITLE
Loading more than 100 posts?

### ISSUE THREAD

**Issue by ModWilliam** [thatJavaNerd/JRAW#146]
I am having issues with loading more than 100 posts at a time. At the moment, the code that I am using to get an ArrayList of submissions is

`

            SubredditPaginator sp = new SubredditPaginator(redditClient, params[0]);
            sp.setLimit(25 * currentPage);

            ArrayList<Submission> posts = new ArrayList<>(sp.next());
            return posts;`

When the parameter for sp.setLimit is over 100, no additional posts are loaded into the ArrayList. What am I doing incorrectly?

**Comment by fbis251** [comment]
Generally you want to keep your `SubredditPaginator` instance stored (which means that `new SubredditPaginator()` is only called once every time your app/program launches) if you're doing long-lived operations, for example in an Android app.

`sp.setLimit()` tells reddit to return n posts at a time. Every time you call `sp.next()` reddit will return 25 more posts, so the 2nd time you'd have 50 posts total, the 3rd 75 posts and so on.

Normally you save more time and bandwidth from setting `sp.setLimit(100)` to get 100 posts at a time rather than doing 4 calls with a 25 post limit to get 100 posts, so adjust this according to your needs.

Make sure that you also check for `sp.hasNext()` which will make sure more posts are actually available, for example:

```java
if(sp.hasNext()) {
	 ArrayList<Submission> posts = new ArrayList<>(sp.next());
	 return posts;
}
return null; // You will need to check for null in the caller
```

You can see another example on how to use Paginators here
https://github.com/thatJavaNerd/JRAW/wiki/Paginators

**Comment by ModWilliam** [comment]
Thanks for the answer and overall helpful tips! I didn't know that you just had to keep calling sp.next()
