### ISSUE TITLE
Methods are marked final

### ISSUE THREAD

**Issue by hughwphamill** [thatJavaNerd/JRAW#161]
Hi, I'm just getting to grips with your library and it seems great, thanks for making it.  I have one issue, however, when trying to mock some of the library classes in my unit tests I'm running into trouble because some methods (e.g. SubredditPaginator.accumulate()) are marked final.  While I can switch to the interface I feel that there is some loss of intent in my own class then, as the interface (RedditIterable) doesn't convey the same intent as a class called 'SubredditPaginator'.

I don't think there's much gain to be made from marking library classes final, and the drawback is that it makes testing more difficult.

**Comment by hughwphamill** [comment]
Actually, not just final methods, but final classes in general are causing issues.

**Comment by fbis251** [comment]
I also have some classes that would benefit from the JRAW classes not being marked final. At the moment I have constructors that copy data from the JRAW classes since I can't inherit from them

**Comment by thatJavaNerd** [comment]
@hughwphamill Which classes in particular were causing you trouble because they are final?

**Comment by hughwphamill** [comment]
Hi, specifically I wanted to either mock Submission or at least extend it to create a lightweight one without needing a load of json to instantiate it.

**Comment by thatJavaNerd** [comment]
Although JRAW is not by design an asynchronous library, the biggest use for it is on the Android platform, an environment that plays better with asynchronous applications. JRAW's models are therefore designed to be as close to immutable as possible, and that means that in general all models that are not abstract are final.

If there are reasons outside of testing for making some models non-final I would be open to changing them. Otherwise, I would look into using wrapper classes to test those final classes.

**Comment by hughwphamill** [comment]
Fair enough, I've already worked around the issue by including some hardcoded json files in my test resources, so it's not blocking me. Thanks for taking the time to respond, and again I really like the library, thanks!

**Comment by thatJavaNerd** [comment]
I appreciate it!
