### ISSUE TITLE
How to turn off logging? 

### ISSUE THREAD

**Issue by plingampally** [thatJavaNerd/JRAW#42]
This is the code i've tried: 

```java
HttpLogger logger = new HttpLogger(JrawUtils.logger());
logger.disable(HttpLogger.Component.REQUEST);
logger.disable(HttpLogger.Component.RESPONSE);
```

I've added the above snippet at various points in the code with no luck (INFO JRAW messages are still displayed) 

I'm using the latest release build v0.6.1

**Comment by thatJavaNerd** [comment]
How are you invoking the logger?

**Comment by janpetryk** [comment]
The issue with logging is bigger than it seems - if you run application with jraw reddit client long enough it will start to use more and more memory since logs that are not written to a file or console are not released and therefore stored in the heap. Memory leak.

For me logging on jraw side should be turned off by default.

@plingampally, I turned off logging by extending RedditClient (a bit hacky, I know) and by placing this code in my new class' constructor:
<code>
for(HttpLogger.Component component : HttpLogger.Component.values()){
            logger.disable(component);
}
</code>

**Comment by thatJavaNerd** [comment]
@plingampally:
 It is not recommended to instantiate a `HttpLogger` yourself, as every `RestClient` has one. The logger can be turned on and off using [`RestClient.setRequestLoggingEnabled()`](https://thatjavanerd.github.io/JRAW/docs/latest/net/dean/jraw/http/RestClient.html#setRequestLoggingEnabled(boolean)).

In the next release, one will be able to get the `RestClient`'s `HttpLogger`, at which point it can be configured by using `HttpLogger.enable(Component)` or `HttpLogger.disable(Component)`. See #27 for more.

@janpetryk:

>if you run application with jraw reddit client long enough it will start to use more and more memory since logs that are not written to a file or console are not released and therefore stored in the heap.

AFAIK, all response InputStreams are read fully into a String using `ResponseBody.string()`, which calls [`ResponseBody.bytes()`](http://grepcode.com/file/repo1.maven.org/maven2/com.squareup.okhttp/okhttp/2.0.0/com/squareup/okhttp/ResponseBody.java#ResponseBody.bytes%28%29), which always closes the `BufferedSource`.

>For me logging on jraw side should be turned off by default.

That is an excellent idea.

**Comment by thatJavaNerd** [comment]
HTTP logging now off by default. See [this commit](https://github.com/thatJavaNerd/JRAW/commit/41f3d6bc5d7dcb01f0d1b79f2418aeab927b7b24).

**Comment by janpetryk** [comment]
When is next maven release?

**Comment by thatJavaNerd** [comment]
It should be within the next week, if not sooner.
