### ISSUE TITLE
Ability to override Host

### ISSUE THREAD

**Issue by natieklopper** [thatJavaNerd/JRAW#61]
I'm using JRAW in an Android Wrapper, it is a lib to my Android app I'm working on.
I would like to add tests to my JRAW Android Wrapper Library using Wiremock, for this I would need to be able to set the host via RedditClient.setHost() and setSpecialHost(). Also to set the Port and HTTP/HTTPS.

Can these please be added?
I don't wan't to have the source of JRAW and edit that, at the moment I'm just using it via Gradle as a library.

Thank you.

**Comment by natieklopper** [comment]
I know I can just override RedditClient and set Restclient host there, but it would be nice to be able to set Host before ResClient gets created.

**Comment by thatJavaNerd** [comment]
This is not something I would like to include in the library, as it is not necessary for most developers to change the host. If you find it absolutely necessary to alter the default host, you can accomplish same effect (to a certain degree) by overriding `HttpClient.request()`:

```java
@Override
public HttpRequest.Builder request() {
    return super.host(MY_HOST);
}
```

This will alter the host of most requests, since most methods use requests formed using `HttpClient.request()`. Note that some methods explicitly state the domain for the request, especially ones that revolve around OAuth.
