### ISSUE TITLE
How to serialize or save RedditClient instance state

### ISSUE THREAD

**Issue by phanghos** [thatJavaNerd/JRAW#68]
I am developing a Reddit client for Android, and I would like to save the state of a RedditClient instance so that there is no need for the user to authorize the app everytime it is opened. Any ideas? I can't serialize the object neither with Gson or Jackson, and I can't think of any other approach to saving the object.

**Comment by thatJavaNerd** [comment]
This is what a refresh token is for. If you save the value of `OAuthHelper.getRefreshToken()`, then the next time you launch the app you can do this:

```java
OAuthHelper helper = reddit.getOAuthHelper();
helper.setRefreshToken("my saved refresh token");
OAuthData newData = helper.refreshToken();
reddit.authenticate(newData);
```

See [here](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2#refreshing-access-tokens) for more.

**Comment by phanghos** [comment]
I get it. What was confusing to me was the Javadoc for the refreshToken() method: "Refreshes the access token. Must have requested an access token when calling {@link #getAuthorizationUrl}." I thought I would need to go through the authorization process all over again everytime I set up a new RedditClient instance, that is, everytime the app is opened. I have another question though. Let's say the user authorizes the app and is given both an access and a refresh token. If he then doesn't open the app again in, say, 5 hours, would that refresh token that was never used still work?

**Comment by fbis251** [comment]
The reddit API will return a token unique to the user/app combination you used when requesting the token. This token should remain valid until the user rejects the token by hand through the reddit preferences page or until you request the token to be invalidated using the JRAW API.

Since you're on Android, the easiest way to store the token would be using [SharedPreferences](https://developer.android.com/training/basics/data-storage/shared-preferences.html) although you should look for more secure storage solutions for the long term.

**Comment by phanghos** [comment]
Thank you!
