### ISSUE TITLE
The README is out of date.

### ISSUE THREAD

**Issue by colinrtwhite** [thatJavaNerd/JRAW#90]
The link for the :testingUser command is broken + I can't find that subproject in the code.

**Comment by thatJavaNerd** [comment]
I had to ditch the project because JRAW now runs on only OAuth2. OAuth2 doesn't let you create accounts or OAuth2 apps (the first two steps in its process). It worked pretty well while it lasted but it's not worth maintaining anymore. I might bring it back but for now it's going to stay dead.

I'll make sure to update the readme appropriately.
