### ISSUE TITLE
The OkHttpClient doesn't wrap enqueue

### ISSUE THREAD

**Issue by Danm72** [thatJavaNerd/JRAW#92]
Passing a callback and not returning from 
```RestResponse execute(HttpRequest request) throws IOException;```

Would avoid the need to wrap jraw calls in async blocks.

So: ```void execute(HttpRequest request, Callback) throws IOException;```

Thoughts?

**Comment by thatJavaNerd** [comment]
What is the Callback class? Is it from OkHttp or JRAW? The reason I ask is because HttpAdapter was designed to be generic, so requiring a class from another library defeats the purpose. I do like what you're thinking though.

**Comment by Danm72** [comment]
In this case it was the okhttp callback class, but really its just an interface if jraw has one then that'll do just grand.

There are a lot of calls to execute in the code that would need altering and I'm trying to figure out if its better to have the library synchronous and then just wrap the client calls in asynchronous blocks or to async up the library.

I'm not sure how people are handling this at the moment, maybe RX Java or one of the other hip libraries is being used to wrap these calls.

**Comment by thatJavaNerd** [comment]
I never actually intended this library for use in Android, so my original thought process was to build the library as a synchronous one since It's generally more predictable. Wrapping JRAW with an asynchronous library would be best at this point as I have no intention of changing the flow to be asynchronous.
